version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./Gateway
    ports:
      - "8000:8000"

  character:
    container_name: characters
    restart: always
    build: ./Characters_api
    ports:
      - "8001:8001"
      
  films:
    container_name: films
    restart: always
    build: ./Films_api
    ports:
      - "8002:8002"

  planet:
    container_name: planets
    restart: always
    build: ./Planets_api
    ports:
      - "8003:8003"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8004:8004"
    env_file:
      - ./database/.env